version: '3.5'

services:
  app:
    build: .
    command: npm run build
    environment:
      NODE_ENV: development
    ports:
      - '8082:3000'
    volumes:
      - .:/home/app/appDir
      - /home/app/appDir/node_modules